name: Build and test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Environment setup
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: json, mbstring
      - name: Install pnpm
        run: npm i -g pnpm
      
      # Install dependencies
      - name: Install dependencies with pnpm
        run: pnpm install
      - name: Install dependencies with composer
        run: composer install
      
      # Build and generate code
      - name: Build TypeScript
        run: pnpm build
      - name: Generate JsonSchema
        run: pnpm schema
      - name: Split JsonSchema
        run: pnpm split
      - name: Generate PHP
        run: pnpm generate
      
      # Run tests
      - name: Test
        run: pnpm test
      
      # PHP Repo Sync
      - name: Load SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.PHP_SECRET }}
      - name: Publish php source code to TECSAFE/jwt-sdk-php repository
        run: |
          git config --global user.email "noreply@tecsafe.de"
          git config --global user.name "CI Bot"
          git clone git@github.com:TECSAFE/jwt-sdk-php.git
          rm -rf jwt-sdk-php/*
          mkdir -p jwt-sdk-php/src
          cp -r src/php/ jwt-sdk-php/src/
          cp LICENSE composer.json composer.lock jwt-sdk-php/
          echo "WARNING: This repository is automatically generated from the jwt-sdk repository." > jwt-sdk-php/README.md
          echo "Do not edit files in this repository directly." >> jwt-sdk-php/README.md
          echo "" >> jwt-sdk-php/README.md
          cat README.md >> jwt-sdk-php/README.md
          cd jwt-sdk-php
          git add .
          git commit -m "Update to version $(echo $GITHUB_REF | sed 's/refs\/tags\///')"
          git push
