name: Build and test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Environment setup
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: json, mbstring
      - name: Install pnpm
        run: npm i -g pnpm
      
      # Install dependencies
      - name: Install dependencies with pnpm
        run: pnpm install
      - name: Install dependencies with composer
        run: composer install
      
      # Build and generate code
      - name: Build TypeScript
        run: pnpm build
      - name: Generate JsonSchema
        run: pnpm schema
      - name: Split JsonSchema
        run: pnpm split
      - name: Generate PHP
        run: pnpm generate
      
      # Run tests
      - name: Test
        run: pnpm test
